config/routes.rb
Rails.application.routes.draw do
   root 'application#welcome'
   get '/signin', to: 'sessions#new'
   post '/signin', to: 'sessions#create'
   get '/signup', to: 'users#new'
   get '/auth/facebook/callback' => 'sessions#create'
   match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
   get 'logout', to: 'sessions#destroy'

   resources :goals
   resources :comments

   resources :users do 
      resources :goals, only: [:show, :index]
   end
   resources :goals do 
      resources :comments, only: [:show, :new, :index, :create]
   end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user 
    belongs_to :goal
end

app/models/goal.rb
class Goal < ApplicationRecord
    belongs_to :user 
    has_many :comments
    has_many :users, through: :comments 
    validates_presence_of :name, message: "Description can't be blank"
    validates_presence_of :goal_amount, message: "Goal Amount can't be blank"
    scope :most_recent, -> { order('created_at desc') }
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    serialize :current_goals, Array 
    serialize :goals_completed, Array
    has_many :goals 
    has_many :comments, through: :goals   
    validates :first_name, length: {minimum: 2, message: "First name must contain at least 2 characters"}
    validates :last_name, length: {minimum: 2, message: "Last name must contain at least 2 characters"} 
    validates :username, uniqueness:  { message: "A user is already registered with that Username."}
    validates_format_of :email, :with => /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i, :message => 'Please enter a valid email address.'
    validates :email, uniqueness: { message: 'A user already has that email.' } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :logged_in?
    helper_method :current_user
    helper_method :finished_goals
    helper_method :goal_completed?

    
    def welcome 
    end

    def logged_in?
        if session[:user_id] != nil 
            true 
        else 
            flash[:notice] = "Must be logged in to see that page!"
            redirect_to '/' 
        end
    end


    def current_user 
        user = User.find_by(id: session[:user_id])
        if user 
          user 
        else 
          nil 
        end
    end


    def goal_completed?(goal)
        if goal.save && goal.goal_progress == goal.goal_amount
            goal.user.goals_completed << goal unless goal.user.goals_completed.include?(goal)
            goal.user.save
            render 'congrats'
        elsif goal.save 
            redirect_to goal_path(goal)
        else 
            render "edit"
        end
    end

    def finished_goals(user) 
        user.goals.each do |goal| 
            if goal.goal_amount == goal.goal_progress 
                user.goals_completed << goal unless user.goals_completed.include?(goal)
                user.save 
            end
        end
        user.goals_completed
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController 
    before_action :logged_in?, only: [:edit, :new, :create, :update, :destroy]
    before_action :comment_find, only: [:edit, :update, :destroy, :show]
    
    def new 
        @comment = Comment.new
        if params[:goal_id]
            @goal = Goal.find(params[:goal_id])
        end
    end

    def create 
        @comment = Comment.create(comment_params)
        if @comment.save 
            redirect_to goal_path(@comment.goal_id)
        end
    end

    def edit 
    end

    def update 
        @comment.update(comment_params) 
        redirect_to goal_path(@comment.goal_id)
    end

    def index
        @goal = Goal.find(params[:goal_id])
        @comments = @goal.comments
    end

    def destroy 
        @goal = @comment.goal_id
        @comment.delete 
        redirect_to goal_path(@goal)
    end

    def show 
    end

    private 

    def comment_find 
        @comment = Comment.find(params[:id])
    end

    def comment_params 
        params.require(:comment).permit(:content, :user_id, :goal_id)
    end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController 
    before_action :goal_find, only: [:edit, :update, :destroy]
    before_action :logged_in?, only: [:edit, :new, :index, :show, :create, :update, :destroy]

    def index 
        if params[:user_id]
            @goals = User.find(params[:user_id]).goals
            @comment = Comment.new  
        else 
            @goals = Goal.most_recent
            @comment = Comment.new 
        end
    end 

    def new
        @goal = Goal.new  
    end 

    def edit 
    end 

    def update 
        @goal.update(goal_params)
        goal_completed?(@goal)
    end

    def create
        @goal = Goal.create(goal_params)
        @goal.user_id = current_user.id 
      
        if @goal.save 
            redirect_to goal_path(@goal)
        else 
            render 'new'
        end  
    end

    def show 
        if Goal.find_by(id: params[:id])
            @goal = Goal.find(params[:id])  
            @comment = Comment.new
        else 
            redirect_to '/'
        end 
    end

    def destroy 
        @goal.destroy
        redirect_to goals_path
    end

    private 

    def goal_find 
        @goal = Goal.find(params[:id])  
    end

    def goal_params 
        params.require(:goal).permit(:name, :goal_amount, :uom, :goal_progress)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 
    def new 
        @user = User.new 
    end

    def create  
        if request.env['omniauth.auth']
            @user = User.find_or_create_by(email: request.env['omniauth.auth'][:info][:email], id: request.env['omniauth.auth'][:uid], first_name: request.env['omniauth.auth'][:info][:name].split[0], last_name: request.env['omniauth.auth'][:info][:name].split[1], username: request.env['omniauth.auth'][:info][:name]) 
            if @user.password == nil 
                @user.password = "#{@user.id}" 
                if @user.save && @user.authenticate(@user.password)
                    session[:user_id] = @user.id
                    redirect_to user_path(@user)
                end
            end
        else
            @user = User.find_by(username: params[:username]) 
            if @user && @user.authenticate(params[:password])
                session[:user_id] = @user.id 
                redirect_to user_path(@user)
            else 
                flash[:notice] = "No user found with those credentials"
                render 'new'
            end
        end 
     end


     def destroy 
        session.delete :user_id
        redirect_to "/"
     end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
    def new
        @user = User.new 
    end

    def create  
        @user = User.create(user_params)
        if @user.save 
            session[:user_id] = @user.id 
            redirect_to user_path(@user)
        else 
            render :new
        end
    end

    def show  
        @user = User.find(params[:id])
    end

    private 

    def user_params 
        params.require(:user).permit(:first_name, :last_name, :username, :password, :email)
    end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
   
  
end

app/views/application/welcome.html.erb
<h3><div style="text-align: center"><%= flash[:notice]  %></div></h3>
<h1><div style="text-align: center">Welcome to StepUP</div></h1> 
<h2><div style="text-align: center">The Home of Motivation since 10/20/2020</div></h2>
<img src= https://www.suwn.org/storage/images/stepup-logos/Step-Up-logo_no_tagline.jpg width="1000" height="500" class="center">

app/views/comments/edit.html.erb
<%= form_for @comment do |c| %> 
    <%= c.label :content %> 
    <%= c.text_field :content %> 
    
    <%= c.submit "Edit Comment" %>
<% end %>

app/views/comments/index.html.erb
<h1>Comments On <%= @goal.name %></h1>
<% @comments.each do |c| %>     
   
    <div class="comment">
   
        <p><%= c.content %></p>
        </div>
        <p>Posted by: <%= c.user.username %></p> 
        <% if c.user == current_user %> 
            <%= button_to "Edit your Comment", edit_comment_path(c), method: "get" %> 
            <%= button_to "Delete your Comment", comment_path(c), method: "delete" %>
        <% end %>
        <br>
        
    <% end %>


<br>  
<br>
<br>

app/views/comments/new.html.erb
<br>
<%= form_for @comment do |c| %> 
    <%= c.label :content %> 
    <%= c.text_field :content %> 
    <%= hidden_field_tag("comment[goal_id]", @goal.id) %>
    <%= hidden_field_tag("comment[user_id]", current_user.id) %>
    <%= c.submit "Add New Comment" , id: @goal.id%>
<% end %>

app/views/comments/show.html.erb
 <br>
    <div class="comment">
   
        <p><%= @comment.content %></p>
        </div>
        <p>Posted by: <%= @comment.user.username %></p> 
        <% if @comment.user == current_user %> 
            <%= button_to "Edit your Comment", edit_comment_path(@comment), method: "get" %> 
            <%= button_to "Delete your Comment", comment_path(@comment), method: "delete" %>
        <% end %>
        <br>

app/views/goals/_form.html.erb
<br>
<h1><%= goal.name %></h1>
<p>Goal Finished at: <%= "#{goal.goal_amount} #{goal.uom}" %></p>
<p>Currently at: <%= goal.goal_progress %> <%= goal.uom %> </p>
<p>Posted by: <%= goal.user.username %></p>
<% if goal.user == current_user %> 
    <%= button_to "Goal Page", goal_path(goal), method: "get" %>
    <%= button_to "Edit Goal", edit_goal_path(goal), method: "get" %>
    <%= button_to "Delete Goal", goal_path(goal), method: "delete" %>
<% end %>

<% if goal.comments.any? %>
<br>
<h2>Comment Section</h2>    
<% goal.comments.each do |c| %>     
   
    <div class="comment">
   
        <p><%= c.content %></p>
        </div>
        <p>Posted by: <%= c.user.username %></p> 
        <% if c.user == current_user %> 
            <%= button_to "Edit your Comment", edit_comment_path(c), method: "get" %> 
            <%= button_to "Delete your Comment", comment_path(c), method: "delete" %>
        <% end %>
        <br>
        
    <% end %>
<% end %>

<br>  
<p>Add new comment!</p>
<%= form_for @comment do |c| %> 
    <%= c.label :content %> 
    <%= c.text_field :content %> 
    <%= hidden_field_tag("comment[user_id]", current_user.id) %>
    <%= hidden_field_tag("comment[goal_id]", goal.id) %>
    <%= c.submit "Add Comment" %>
<% end %>
<br>
<br>

app/views/goals/congrats.html.erb
<h1> Congrats!! <%= @goal.user.username %> on completing <%= @goal.user.goals_completed.uniq.length %> goal(s) on Step Up! </h1>

app/views/goals/edit.html.erb
<% if logged_in? %>
    <% if current_user.id == @goal.user_id %>
<h1>Edit your Goal!</h1>
<% if @goal.errors.any? %>
    <div class="errors_explanation", style="padding: 20px">
        <% @goal.errors.values.each do |m| %>
            <p><%= m.to_sentence %></p>
        <% end %>
    </div>
<% end %>
<%= form_for @goal do |f| %> 
    <%= f.label "description of goal" %> 
    <%= f.text_field :name, value: @goal.name%><br>
    <%= f.label "What is your goal amount?" %> 
    <%= f.text_field :goal_amount %><br> 
    <%= f.label "What is your updated progress towards your goal amount?"%>
    <%= f.text_field :goal_progress %><br>
    <%= f.text_field :uom, placeholder: "I.E. Pounds, Dollars, Days, Etc." %><br>
    <%= f.submit %>
    <% end %>
    <% else %> 
    <% redirect_to "/" %>
 <% end %>
 <% else %>
  <% redirect_to "/" %>
 <% end %>

app/views/goals/index.html.erb
<% @goals.each do |goal| %> 
    <%= render partial: 'form', locals: {goal: goal} %> 
<% end %> 

app/views/goals/new.html.erb
<% if logged_in? %> 
<h1>Post a new Goal!</h1>
<% if @goal.errors.any? %>
    <div class="errors_explanation", style="padding: 20px">
        <% @goal.errors.values.each do |m| %>
            <p><%= m.to_sentence %></p>
        <% end %>
    </div>
<% end %>
<%= form_for @goal do |f| %> 
    <%= f.label "description of goal" %> 
    <%= f.text_field :name %><br>
    <%= f.label "What is your goal amount?" %> 
    <%= f.text_field :goal_amount %><br> 
    <%= f.label "What is the unit of measurement for your goal?" %> 
    <%= f.text_field :uom, placeholder: "I.E. Pounds, Dollars, Days, Etc." %><br>
    <%= f.submit %>
<% end %>
<% end %>

app/views/goals/show.html.erb
<%= render partial: 'form', locals: {goal: @goal} %>

app/views/layouts/application.html.erb
  
<!DOCTYPE html>
<html>
  <head>
    <title>Step Up</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Bootstrap Core CSS -->
  <link href="../vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom Fonts -->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
 
  <!-- Custom CSS -->
  <link href="../css/stylish-portfolio.min.css" rel="stylesheet">

  </head>
  <% if !current_user %>
    <div class="topnav">
      <%= link_to "Sign Up", signup_path %>
      <%= link_to "Log In", signin_path %>
      <%= link_to('Log in with Facebook!', '/auth/facebook') %>
    </div>

    <% else %>

    <div class="topnav">
      <%= link_to "My Home", user_path(current_user)%>
      <%= link_to "Post a new Goal", new_goal_path %>
      <%= link_to "Goals you've posted onto Step Up", user_goals_path(current_user) %> 
      <%= link_to "All Goals posted onto Step Up", goals_path %> 
      <%= link_to "Log Out", logout_path %>
    </div>

    <% end %>

  <body>
    <%= yield %>
  </body>
  
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %> 
    <%= f.label "First Name:" %><br>
    <%= f.text_field :first_name %><br>
    <%= f.label "Last Name:" %><br>
    <%= f.text_field :last_name %><br>
    <%= f.label :email %><br>
    <%= f.text_field :email %><br>
    <%= f.label :username %><br>
    <%= f.text_field :username %><br>
    <%= f.label :password %> <br>
    <%= password_field_tag "user[password]" %><br>
    <%= f.label :password_confirmation %><br>
    <%= password_field_tag :password_confirmation %><br><br>
<%= f.submit "Sign Up" %>
<% end %> 

app/views/users/new.html.erb
<h1>User Sign Up!</h1>
<% if @user.errors.any? %>
    <div class="errors_explanation", style="padding: 20px">
        <% @user.errors.values.each do |m| %>
            <p><%= m.to_sentence %></p>
        <% end %>
    </div>
<% end %>
<%= render 'form' %> 

app/views/users/show.html.erb
<h1>Hello! <%= @user.username%></h1>
<% if @user.goals_completed %>
    <h2>Completed Goals</h2>
    <% @user.goals_completed.each do |goal| %>
        <p>Goal Name: <%= goal.name %> 
        <%= link_to "Goal Page", goal_path(goal) %>
        <% end %> 
    <% end %>